version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: trading-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: trading-bot-backend
    env_file:
      - ../backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - trading-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: trading-bot-frontend
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - trading-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  trading-network:
    driver: bridge
